analyzer:
  errors:
    use_build_context_synchronously: ignore
    invalid_annotation_target: ignore
    unused_element_parameter: ignore
    deprecated_member_use: ignore
    sdk_version_since: ignore
    avoid_print: ignore
    file_names: ignore
    curly_braces_in_flow_control_structures: ignore
    unnecessary_string_interpolations: ignore
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_relative_imports: true